### ISSUE TITLE
Is it possible to run this for all yarn.lock files? 

### ISSUE THREAD

**Issue by GocoolGK** [lirantal/lockfile-lint#156]
Currently from the existing CLI commands we are able to provide the exact yarn.lock file path alone. So, we have to configure/run recursively with exact yarn.lock file path locations(subdirectorys yarn.lock files).

Please let me know if we have an option for this(to check all subdirectory's yarn.lock files)? like */yarn.lock

**Comment by lirantal** [comment]
Hi @GocoolGK 

I assume the need here is because you are managing a monorepo or something like it with many projects that include a `yarn.lock` file colocated in the same repository?

This brings up a few questions in terms of way of how to support it:
- Would you want to match both npm's and yarn's lockfiles in an automated way? as in, just locate any files under a given glob pattern that matches one of those file names?
- What is the behavior if some out of all the files scanned have an issue, does the command fail?
- How do you expect to get the report back? just continuous output one after another?

If you could share a bit more into the expected behavior then we can try and ideate a path for this new feature.

**Comment by lirantal** [comment]
Thanks!
