### ISSUE TITLE
PackageError module is not used.

### ISSUE THREAD

**Issue by bolatovumar** [lirantal/lockfile-lint#78]
As the title says, `PackageError` module is defined but never used anywhere.

See here: https://github.com/lirantal/lockfile-lint/blob/master/packages/lockfile-lint-api/src/common/PackageError.js#L3

**Comment by lirantal** [comment]
Indeed, that's due to the refactor we did that swallowed errors (https://github.com/lirantal/lockfile-lint/blob/a089214722c2cc355bd6be602b7af475acf247a5/packages/lockfile-lint-api/src/validators/ValidateScheme.js#L42-----L43).

I think it's safe to remove for now and if we need in the future we can re-add it.

**Comment by XhmikosR** [comment]
@lirantal this can be also closed 🙂 (`Address` does not close the referenced issue 😛)

**Comment by lirantal** [comment]
Yes! oooof I really miss semantic-release for monorepos 🙃
Thanks!
